# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
#https://release.com/blog/how-to-create-and-configure-your-kubernetes-service-account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: default